# Generated by Django 4.1.5 on 2023-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_id',
            field=models.CharField(max_length=20, null=True, verbose_name='Card ID'),
        ),
    ]
