# Generated by Django 4.1.5 on 2023-01-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Updated at'),
        ),
    ]
