# Generated by Django 4.1.5 on 2023-02-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tna_system', '0004_event_event_category_event_is_deleted_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tna_system.eventcategory', verbose_name='Event category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tna_system.location', verbose_name='Location'),
        ),
    ]
