# Generated by Django 4.1.5 on 2023-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna_system', '0005_alter_event_event_category_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Updated at'),
        ),
    ]
