# Generated by Django 4.1.5 on 2023-02-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna_system', '0006_alter_event_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='0=RFID 1=BT'),
        ),
    ]
